#!/usr/bin/env python3
"""Create the stream_len gold wrapper: packs the unpacked `axi_config_t`
array port of ethosu55_dma_stream_len into a single [87:0] vector so the
EQY gold top has the same packed port list as the PyCDE-generated gate.

Output: build/gold_ref/stream_len_gold_wrapper.sv
(contains `stream_len_gold`, instantiating the renamed ARM module
`ethosu55_dma_stream_len_gold`, which must be renamed first by
make_gold_renames.py).
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WRAPPER = '''//-----------------------------------------------------------------------------
// mini-npu EQY wrapper (generated by script/make_gold_wrapper_stream_len.py)
//
// Packs axi_config_t = axi_config_elem_t[3:0] (unpacked) into [87:0].
// Element i occupies bits [22*i +: 22]; inside each 22-bit element the
// packed struct members sit MSB-first:
//   { max_beats[1:0], memtype[3:0], max_outst_rd[7:0], max_outst_wr[7:0] }
//-----------------------------------------------------------------------------
module stream_len_gold
  import ethosu55_pkg::*;
  import ethosu55_cc_reg_pkg::*;
  import ethosu55_dma_pkg::*;
(
  input  wire        asrt_clk,
  input  wire        asrt_rst_n,
  input  wire [1:0]  stream_type_i,
  input  wire [31:0] addr_i,
  input  wire [27:0] rem_len_i,
  input  wire [1:0]  region_i,
  input  wire [87:0] axi_cfg_i,
  output wire [7:0]  calc_len_o
);
  axi_config_t axi_cfg_unpk;

  for (genvar r = 0; r < 4; r = r + 1) begin: g_cfg
    assign axi_cfg_unpk[r] = axi_config_elem_t'(axi_cfg_i[r*22 +: 22]);
  end

  ethosu55_dma_stream_len_gold u_dut (
    .asrt_clk      (asrt_clk),
    .asrt_rst_n    (asrt_rst_n),
    .stream_type_i (stream_type_t'(stream_type_i)),
    .addr_i        (addr_i),
    .rem_len_i     (len_words_t'(rem_len_i)),
    .region_i      (region_t'(region_i)),
    .axi_cfg_i     (axi_cfg_unpk),
    .calc_len_o    (calc_len_o)
  );
endmodule
'''


def main():
    outdir = os.path.join(ROOT, "build", "gold_ref")
    os.makedirs(outdir, exist_ok=True)
    out = os.path.join(outdir, "stream_len_gold_wrapper.sv")
    with open(out, "w") as fh:
        fh.write(WRAPPER)
    print(out)


if __name__ == "__main__":
    main()
