#!/usr/bin/env python3
"""Create gold-side module copies.

For each ARM reference module we produce build/gold_ref/<m>_gold.sv with:
  * module renamed to <m>_gold (so gold and gate never collide in one yosys
    design), ports and logic untouched.
  * parameter overrides baked in as localparams for the chosen instance
    configuration (N=4/W=8 for onehot_mux).
  * unused-warning-safe: `asrt_*` ports stay (port lists must match).

Additionally builds stream_len_gold_wrapper.sv: unpacked-array port
adaptation. The ARM top has `axi_config_t axi_cfg_i` (unpacked [3:0] of
22-bit elements); the PyCDE gate has a packed [87:0] input. The wrapper
(module stream_len_gold) exposes the packed view and feeds the original
module, keeping bit layout identical to the gate side.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "rtl_ref")
OUT = os.path.join(ROOT, "build", "gold_ref")

# module -> (source file, new top name, extra localparam overrides)
MODULES = {
    "bin2onehot": ("ethosu55_bin2onehot.sv", {}),
    "onehot_mux": ("ethosu55_onehot_mux.sv", {"N": "4"}),
    "rr_arb": ("ethosu55_rr_arb.sv", {"WIDTH": "6"}),
    "rr_reg_arb": ("ethosu55_rr_reg_arb.sv", {"WIDTH": "6"}),
    "or_tree_w6": ("ethosu55_or_tree_w6.sv", {}),
    "back_buf": ("ethosu55_back_buf.sv", {"DEPTH": "3", "WIDTH": "64"}),
    "reg_fifo": ("ethosu55_reg_fifo.sv",
                 {"FIFO_WIDTH": "32", "FIFO_DEPTH": "16"}),
    "multi_pipe_stage": ("ethosu55_multi_pipe_stage.sv",
                         {"WIDTH": "64", "NUM_READERS": "2"}),
    "stream_len": ("ethosu55_dma_stream_len.sv", {}),
}


def rename_module(text: str, old: str, new: str, overrides: dict) -> str:
    m = re.search(rf"module\s+{old}\s*#\((.*?)\)\s*\((.*?)\);",
                  text, re.S)
    if not m:
        # no parameter port list:  module X  <imports...> ( ports );
        m = re.search(rf"module\s+{old}\b(.*?\);)", text, re.S)
        assert m, f"cannot find module {old}"
        ports_src = m.group(1)
        header = f"module {new}{ports_src}"
    else:
        params_src, ports_src = m.group(1), m.group(2)
        localparams = "".join(
            f"\n  localparam {k} = {v};" for k, v in overrides.items())
        header = (f"module {new} #() (\n{ports_src}\n);\n"
                  f"{localparams}\n")
    body = text[m.end():]
    # keep everything up to the matching endmodule
    end = body.rfind("endmodule")
    body = body[:end]
    out = (f"// Auto-generated by make_gold_renames.py -- do not edit.\n"
           f"// Source: rtl_ref/  module {old}\n"
           f"{text[:m.start()]}\n{header}\n{body}\nendmodule\n")
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, (src, overrides) in MODULES.items():
        path = os.path.join(REF, src)
        text = open(path).read()
        if name == "stream_len":
            old = "ethosu55_dma_stream_len"
        else:
            old = "ethosu55_" + name
        new = f"{name}_gold"
        out = rename_module(text, old, new, overrides)
        dst = os.path.join(OUT, f"{name}_gold.sv")
        with open(dst, "w") as f:
            f.write(out)
        print("wrote", dst)

    # stream_len gold wrapper: packed axi_cfg -> unpacked
    wrapper = """\
// Auto-generated by make_gold_wrapper_stream_len.py -- do not edit.
// Packed view of axi_config_t = axi_config_elem_t[3:0]; element r occupies
// bits [22*r +: 22], matching the PyCDE gate-side packed port layout.
module stream_len_gold
  import ethosu55_pkg::*;
  import ethosu55_cc_reg_pkg::*;
  import ethosu55_dma_pkg::*;
(
  input  wire                  asrt_clk,
  input  wire                  asrt_rst_n,
  input  wire [1:0]            stream_type_i,
  input  wire [31:0]           addr_i,
  input  wire [28:0]           rem_len_i,
  input  wire [1:0]            region_i,
  input  wire [87:0]           axi_cfg_i,
  output wire [7:0]            calc_len_o
);
  axi_config_t axi_cfg_unpk;

  for (genvar r = 0; r < 4; r = r + 1) begin: g_cfg
    assign axi_cfg_unpk[r] = axi_config_elem_t'(axi_cfg_i[r*22 +: 22]);
  end

  ethosu55_dma_stream_len u_dut (
    .asrt_clk      (asrt_clk),
    .asrt_rst_n    (asrt_rst_n),
    .stream_type_i (stream_type_t'(stream_type_i)),
    .addr_i        (addr_i),
    .rem_len_i     (len_words_t'(rem_len_i)),
    .region_i      (region_t'(region_i)),
    .axi_cfg_i     (axi_cfg_unpk),
    .calc_len_o    (calc_len_o)
  );
endmodule
"""
    dst = os.path.join(OUT, "stream_len_gold_wrapper.sv")
    with open(dst, "w") as f:
        f.write(wrapper)
    print("wrote", dst)


if __name__ == "__main__":
    main()
